import type { Metadata } from "next";
import { SessionProvider } from "./providers";
import { WalletProvider } from "./WalletContext"; // Import WalletProvider
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head"; // Import Head

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const ppNeueMachina = localFont({
  src: [
    {
      path: "./fonts/PPNeueMachina-PlainLight.otf",
      weight: "300",  
      style: "normal",
    },
    {
      path: "./fonts/PPNeueMachina-PlainRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/PPNeueMachina-PlainUltrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/PPNeueMachina-PlainUltraboldItalic.otf",
      weight: "800",
      style: "italic",
    },
    {
      path: "./fonts/PPNeueMachina-PlainRegularItalic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/PPNeueMachina-PlainLightItalic.otf",
      weight: "300",
      style: "italic",
    },
  ],
  variable: "--font-pp-neue-machina",
});

export const metadata: Metadata = {
  title: "AI Guardan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>AI Guardian</title>
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ppNeueMachina.variable} antialiased max-w-screen`}
      >
        {/* Wrap with WalletProvider as well as SessionProvider */}
        <SessionProvider>
          <WalletProvider>{children}</WalletProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
